/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.mymuseum.interfaces;

import br.edu.mymuseum.classe.Funcionario;
import br.edu.mymuseum.classe.Guardinha;
import br.edu.mymuseum.classe.Restaurador;
import br.edu.mymuseum.dao.DaoFuncionario;
import br.edu.mymuseum.validacao.LimparCampos;
import br.edu.mymuseum.validacao.PreencherJtableGenerico;
import br.edu.mymuseum.validacao.Rotinas;
import br.edu.mymuseum.validacao.UltimaSequencia;
import br.edu.mymuseum.validacao.ValidaBotoes;
import javax.swing.JOptionPane;

/**
 *
 * @author Dorga
 */
public class Func extends javax.swing.JFrame {

    ValidaBotoes validabotoes = new ValidaBotoes();
    int situacao = Rotinas.PADRÃO;
    Funcionario funcionario = new Funcionario();
    DaoFuncionario daofuncionario = new DaoFuncionario();
    Restaurador restaurador = new Restaurador();
    Guardinha guarda = new Guardinha();
    UltimaSequencia ultima;
    int sequencia = 0;
    LimparCampos limparcampos = new LimparCampos();
    PreencherJtableGenerico preenchertable = new PreencherJtableGenerico();

    public Func() {
        initComponents();
        validabotoes.ValidaEstado(jPanel3, Rotinas.PADRÃO);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cd_funcionario = new javax.swing.JTextField();
        nm_funcionario = new javax.swing.JTextField();
        cpf = new javax.swing.JTextField();
        sl_funcionario = new javax.swing.JTextField();
        tp_funcionario = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        Novo = new javax.swing.JButton();
        Alterar = new javax.swing.JButton();
        Gravar = new javax.swing.JButton();
        Excluir = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        especialidade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jCbPesquisa = new javax.swing.JComboBox();
        jTfPesquisa = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTbPesquisa2 = new javax.swing.JTable();
        jBtPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nome");

        jLabel2.setText("Cpf");

        jLabel3.setText("Tipo");

        jLabel4.setText("Salario");

        jLabel6.setText("Codigo");

        cd_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cd_funcionarioActionPerformed(evt);
            }
        });

        tp_funcionario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Escolha", "Restaurador", "Guarda" }));
        tp_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tp_funcionarioActionPerformed(evt);
            }
        });

        Novo.setText("Novo");
        Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoActionPerformed(evt);
            }
        });

        Alterar.setText("Alterar");
        Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarActionPerformed(evt);
            }
        });

        Gravar.setText("Gravar");
        Gravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GravarActionPerformed(evt);
            }
        });

        Excluir.setText("Excluir");
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Novo)
                .addGap(18, 18, 18)
                .addComponent(Alterar)
                .addGap(18, 18, 18)
                .addComponent(Gravar)
                .addGap(18, 18, 18)
                .addComponent(Excluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Cancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Novo)
                    .addComponent(Alterar)
                    .addComponent(Gravar)
                    .addComponent(Excluir)
                    .addComponent(Cancelar))
                .addContainerGap())
        );

        especialidade.setEnabled(false);

        jLabel5.setText("Especialidade");
        jLabel5.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(cd_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nm_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(cpf))))
                        .addGap(10, 10, 10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tp_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(sl_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(especialidade)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cd_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nm_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tp_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(especialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sl_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Cadastro", jPanel1);

        jCbPesquisa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Geral", "Código", "Titulo" }));

        jTbPesquisa2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Tipo", "Nome", "Salario", "Cpf"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTbPesquisa2.setToolTipText("");
        jTbPesquisa2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTbPesquisa2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbPesquisa2MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTbPesquisa2);

        jBtPesquisar.setText("Pesquisar");
        jBtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jCbPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtPesquisar))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCbPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consulta", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cd_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cd_funcionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cd_funcionarioActionPerformed

    private void NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoActionPerformed
        situacao = Rotinas.INCLUIR;
        validabotoes.ValidaEstado(jPanel3, situacao);
        cd_funcionario.setEnabled(false);
        ultima = new UltimaSequencia();
        sequencia = (Integer) (ultima.ultimasequencia("FUNCIONARIO", "CD_FUNCIONARIO"));
        cd_funcionario.setText(Integer.toString(sequencia));
        // TODO add your handling code here:
    }//GEN-LAST:event_NovoActionPerformed

    private void AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarActionPerformed
        situacao = Rotinas.ALTERAR;
        validabotoes.ValidaEstado(jPanel3, situacao);
        // TODO add your handling code here:
    }//GEN-LAST:event_AlterarActionPerformed

    private void GravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GravarActionPerformed
        getcomp();
        if (situacao == Rotinas.INCLUIR) {
            daofuncionario.incluir(funcionario);
            if (funcionario.getTp_funcinario() == 1) {
                restaurador.setCd_funcionario(sequencia);
                restaurador.setEspecialidade(especialidade.getText());
                daofuncionario.incluir(restaurador);
            } else if (funcionario.getTp_funcinario() == 2) {
                guarda.setCd_funcionario(sequencia);
                guarda.setTt_guardas(Double.parseDouble(especialidade.getText()));
                daofuncionario.incluir(guarda);
            }
        }else if (situacao == Rotinas.ALTERAR){
            daofuncionario.alterar(funcionario);
            if (funcionario.getTp_funcinario() == 1) {
                restaurador.setCd_funcionario(Integer.parseInt(cd_funcionario.getText()));
                restaurador.setEspecialidade(especialidade.getText());
                daofuncionario.alterar(restaurador);
            } else if (funcionario.getTp_funcinario() == 2) {
                guarda.setCd_funcionario(Integer.parseInt(cd_funcionario.getText()));
                guarda.setTt_guardas(Double.parseDouble(especialidade.getText()));
                daofuncionario.alterar(guarda);
            }
        }
        situacao = Rotinas.PADRÃO;
        limparcampos.LimparCampos(jPanel1);
        validabotoes.ValidaEstado(jPanel3, situacao);

        // TODO add your handling code here:
    }//GEN-LAST:event_GravarActionPerformed

    private void tp_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tp_funcionarioActionPerformed
        if (tp_funcionario.getSelectedIndex() == 1) {
            jLabel5.setText("Especialidade");
            especialidade.setText("");
            especialidade.setEnabled(true);
            jLabel5.setEnabled(true);
        } else if (tp_funcionario.getSelectedIndex() == 2) {
            jLabel5.setText("Total de Horas de guarda");
            especialidade.setText("0.0");
            especialidade.setEnabled(true);
            jLabel5.setEnabled(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tp_funcionarioActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        situacao = Rotinas.PADRÃO;
        validabotoes.ValidaEstado(jPanel3, situacao);
        limparcampos.LimparCampos(jPanel1);
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelarActionPerformed

    private void jTbPesquisa2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbPesquisa2MouseClicked
        if (evt.getClickCount() == 2) {
            int linha = jTbPesquisa2.getSelectedRow();
            String valor = (String) jTbPesquisa2.getValueAt(linha, 0);
            funcionario.setCd_funcionario(Integer.parseInt(valor));
            daofuncionario.retornardados(funcionario);
            setcomp();
            jPanel1.getCursor();
        }
    }//GEN-LAST:event_jTbPesquisa2MouseClicked

    private void jBtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtPesquisarActionPerformed
        // TODO add your handling code here:
        switch (jCbPesquisa.getSelectedIndex()) {
            case 0:
                daofuncionario.consultaGeral(funcionario);
                preenchertable.PreencherJtableGenerico(jTbPesquisa2, new String[]{"CD_FUNCIONARIO", "TP_FUNCIONARIO", "NM_FUNCIONARIO", "SL_FUNCIONARIO", "CPF"}, funcionario.getRetorno());
                break;
            case 1:
                funcionario.setCd_funcionario(Integer.parseInt(jTfPesquisa.getText()));
                daofuncionario.consultaCodigo(funcionario);
                preenchertable.PreencherJtableGenerico(jTbPesquisa2, new String[]{"CD_FUNCIONARIO", "TP_FUNCIONARIO", "NM_FUNCIONARIO", "SL_FUNCIONARIO", "CPF"}, funcionario.getRetorno());
                break;
            case 2:
                funcionario.setNm_funcionario(jTfPesquisa.getText());
                daofuncionario.consultaPessoa(funcionario);
                preenchertable.PreencherJtableGenerico(jTbPesquisa2, new String[]{"CD_FUNCIONARIO", "TP_FUNCIONARIO", "NM_FUNCIONARIO", "SL_FUNCIONARIO", "CPF"}, funcionario.getRetorno());

                break;
        }
    }//GEN-LAST:event_jBtPesquisarActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Confirma a exclusão do registro") == 0) {
            if (!cd_funcionario.getText().equals("")) {
                funcionario.setCd_funcionario(Integer.parseInt(cd_funcionario.getText()));
                
                daofuncionario.excluir(funcionario);
            } else {
                JOptionPane.showMessageDialog(null, "Informe o Código do Funcionário");

            }

        }
    }//GEN-LAST:event_ExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Func.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Func.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Func.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Func.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Func().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Alterar;
    public javax.swing.JButton Cancelar;
    public javax.swing.JButton Excluir;
    public javax.swing.JButton Gravar;
    public javax.swing.JButton Novo;
    public javax.swing.JTextField cd_funcionario;
    public javax.swing.JTextField cpf;
    public javax.swing.JTextField especialidade;
    public javax.swing.JButton jBtPesquisar;
    public javax.swing.JComboBox jCbPesquisa;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTable jTbPesquisa2;
    public javax.swing.JTextField jTfPesquisa;
    public javax.swing.JTextField nm_funcionario;
    public javax.swing.JTextField sl_funcionario;
    public javax.swing.JComboBox tp_funcionario;
    // End of variables declaration//GEN-END:variables

    public void getcomp() {

        funcionario.setCd_funcionario(Integer.parseInt(cd_funcionario.getText()));

        funcionario.setNm_funcionario(nm_funcionario.getText());
        funcionario.setCpf(Long.parseLong(cpf.getText()));
        funcionario.setSl_funcionario(Double.parseDouble(sl_funcionario.getText()));
        if (tp_funcionario.getSelectedIndex() == 1) {
            funcionario.setTp_funcinario(1);
        } else if (tp_funcionario.getSelectedIndex() == 2) {
            funcionario.setTp_funcinario(2);
        } else {
            JOptionPane.showMessageDialog(null, "Escolha um tipo de funcionário");
        }

    }

    public void setcomp() {
        cd_funcionario.setText(Integer.toString(funcionario.getCd_funcionario()));
        nm_funcionario.setText(funcionario.getNm_funcionario());
        sl_funcionario.setText(Double.toString(funcionario.getSl_funcionario()));
        cpf.setText(Long.toString(funcionario.getCpf()));
        if (funcionario.getTp_funcinario() == 1) {
            tp_funcionario.setSelectedIndex(1);
            restaurador.setCd_funcionario(funcionario.getCd_funcionario());
            daofuncionario.retornardados(restaurador);
            especialidade.setText(restaurador.getEspecialidade());
        } else if (funcionario.getTp_funcinario() == 2) {
            tp_funcionario.setSelectedIndex(2);
            guarda.setCd_funcionario(funcionario.getCd_funcionario());
            daofuncionario.retornardados(guarda);
            especialidade.setText(Double.toString(guarda.getTt_guardas()));
        }
    }
}
