/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.mymuseum.interfaces;

import br.edu.mymuseum.classe.ManutencaoMaterial;
import br.edu.mymuseum.classe.ManutencaoObra;
import br.edu.mymuseum.classe.Material;
import br.edu.mymuseum.classe.Obra;
import br.edu.mymuseum.classe.Restaurador;
import br.edu.mymuseum.dao.DaoFuncionario;
import br.edu.mymuseum.dao.DaoManutencao;
import br.edu.mymuseum.dao.DaoManutencaoMaterial;
import br.edu.mymuseum.dao.DaoMaterial;
import br.edu.mymuseum.dao.DaoObra;
import br.edu.mymuseum.validacao.LimparCampos;
import br.edu.mymuseum.validacao.PreencherComboBoxGenerico;
import br.edu.mymuseum.validacao.Rotinas;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dorga
 */
public class GerenciarManutencao extends javax.swing.JFrame {
    
    Material material = new Material();
    DaoMaterial daomaterial = new DaoMaterial();
    Obra obra = new Obra();
    DaoObra daoobra = new DaoObra();
    ManutencaoObra manutencaoobra = new ManutencaoObra();
    ManutencaoMaterial manutencaomaterial = new ManutencaoMaterial();
    PreencherComboBoxGenerico preenchercombo = new PreencherComboBoxGenerico();
    DaoManutencaoMaterial daomanutencaomaterial = new DaoManutencaoMaterial();
    DaoManutencao daomanutencao = new DaoManutencao();
    DaoFuncionario daofuncionario = new DaoFuncionario();
    Restaurador restaurador = new Restaurador();
    int situacao = Rotinas.PADRÃO;
    
    public GerenciarManutencao() {
        initComponents();
        daoobra.consultaEscultura(obra);
        preenchercombo.PreencherComboBoxGenerico(cd_obra, "TI_OBRA", "CD_OBRA", obra.getRetorno());
        daofuncionario.consultaReparador(restaurador);
        preenchercombo.PreencherComboBoxGenerico(cd_funcionario, "NM_FUNCIONARIO", "CD_FUNCIONARIO", restaurador.getRetorno());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cd_funcionario = new javax.swing.JComboBox();
        cd_obra = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dt_inicio = new javax.swing.JTextField();
        dt_fincal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ds_servico = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        custo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        codmaterial = new javax.swing.JTextField();
        psmaterial = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Escolha o Reparador e a Obra"));

        jLabel1.setText("Reparador");

        jLabel2.setText("Obra");

        cd_funcionario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        cd_funcionario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cd_funcionarioFocusLost(evt);
            }
        });

        cd_obra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cd_obraFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cd_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cd_obra, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cd_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cd_obra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Data Ínicio");

        jLabel4.setText("Data Final");

        dt_fincal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dt_fincalActionPerformed(evt);
            }
        });

        jLabel5.setText("Descrição");

        jLabel6.setText("Custo");

        jLabel7.setText("Materiais Necessários para a Manutenção");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sel", "Codigo", "Material", "Quantidade", "Obra", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTable2FocusLost(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jButton1.setText("+");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("-");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel11.setText("Quantidade");

        jLabel12.setText("Código");

        codmaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codmaterialActionPerformed(evt);
            }
        });
        codmaterial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                codmaterialFocusLost(evt);
            }
        });

        psmaterial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                psmaterialFocusLost(evt);
            }
        });

        jButton3.setText("Gerenciar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dt_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dt_fincal, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(95, 95, 95)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ds_servico, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(custo)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(23, 23, 23))
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(psmaterial)
                                    .addComponent(codmaterial)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2)))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dt_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dt_fincal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ds_servico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(custo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codmaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(psmaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dt_fincalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dt_fincalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dt_fincalActionPerformed

    private void jTable2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable2FocusLost

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2FocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        manutencaomaterial.setCd_material(Integer.parseInt(codmaterial.getText()));
        manutencaomaterial.setQt_material(Integer.parseInt(psmaterial.getText()));
        String[] obr = cd_obra.getSelectedItem().toString().split("-");
        String titulo = obr[1].toString();
        obra.setTi_obra(titulo);
        daoobra.consultaObra(obra);
        try {
            obra.getRetorno().first();
            int cdobra = obra.getRetorno().getInt("CD_OBRA");
            manutencaomaterial.setCd_obra(cdobra);
            manutencaomaterial.setTp_obra(obra.getRetorno().getInt("TP_OBRA"));
        } catch (SQLException ex) {
            Logger.getLogger(GerenciarManutencao.class.getName()).log(Level.SEVERE, null, ex);
        }
        manutencaomaterial.setTabela(jTable2);
        daomanutencaomaterial.incluiritens(manutencaomaterial);
        
        codmaterial.setText("");
        psmaterial.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        daomanutencaomaterial.excluiitens(manutencaomaterial);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void codmaterialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codmaterialFocusLost
        // TODO add your handling code here:
        material.setCd_material(Integer.parseInt(codmaterial.getText()));
        daomaterial.consultaCodigo(material);
        try {
            material.getRetorno().first();
            if (material.getRetorno().getString("NM_MATERIA") != null) {
                manutencaomaterial.setDs_material(material.getRetorno().getString("NM_MATERIA"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Insira um material válido");
            codmaterial.setText("");
        }
    }//GEN-LAST:event_codmaterialFocusLost

    private void psmaterialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_psmaterialFocusLost
        // TODO add your handling code here:
        if (!psmaterial.getText().equals("")) {
            daomaterial.consultaCodigo(material);
            try {
                material.getRetorno().first();
                if (Integer.parseInt(psmaterial.getText()) <= material.getRetorno().getInt("QT_ESTOQUE")) {
                    jButton1.setEnabled(true);
                    jButton2.setEnabled(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Quantidade maior do que a do estoque");
                }
            } catch (SQLException ex) {
                Logger.getLogger(GerenciarManutencao.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } else {
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
        }
    }//GEN-LAST:event_psmaterialFocusLost

    private void codmaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codmaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codmaterialActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        getcomp();
        daomanutencao.incluir(manutencaoobra);
        manutencaomaterial.setTabela(jTable2);
        manutencaomaterial.setDt_inicio(dt_inicio.getText());
        daomanutencaomaterial.grava_itens(manutencaomaterial);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cd_funcionarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cd_funcionarioFocusLost
        // TODO add your handling code here:
        cd_funcionario.setEnabled(false);
    }//GEN-LAST:event_cd_funcionarioFocusLost

    private void cd_obraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cd_obraFocusLost
        cd_obra.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_cd_obraFocusLost

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        LimparCampos limpar = new LimparCampos();
        limpar.LimparCampos(jPanel1);
        cd_funcionario.setEnabled(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GerenciarManutencao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GerenciarManutencao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GerenciarManutencao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GerenciarManutencao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GerenciarManutencao().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox cd_funcionario;
    public javax.swing.JComboBox cd_obra;
    public javax.swing.JTextField codmaterial;
    public javax.swing.JTextField custo;
    public javax.swing.JTextField ds_servico;
    public javax.swing.JTextField dt_fincal;
    public javax.swing.JTextField dt_inicio;
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTable2;
    public javax.swing.JTextField psmaterial;
    // End of variables declaration//GEN-END:variables

    public void getcomp() {
        situacao = Rotinas.INCLUIR;
        if (situacao == Rotinas.INCLUIR) {
            String[] cd = cd_funcionario.getSelectedItem().toString().split("-");
            int cd_funcionario = Integer.parseInt(cd[0].toString());
            manutencaoobra.setCd_funcionario(cd_funcionario);
            String[] obras = cd_obra.getSelectedItem().toString().split("-");
            int cd_obra = Integer.parseInt(obras[0].toString());
            manutencaoobra.setCd_obra(cd_obra);
            daoobra.consultaCd(obra);
            int tp_obra = 0;
            try {
                obra.getRetorno().first();
                tp_obra = obra.getRetorno().getInt("TP_OBRA");
            } catch (SQLException ex) {
                Logger.getLogger(GerenciarManutencao.class.getName()).log(Level.SEVERE, null, ex);
            }
            manutencaoobra.setDt_inicio(dt_inicio.getText());
            manutencaoobra.setDt_final(dt_fincal.getText());
            manutencaoobra.setCusto(Double.parseDouble(custo.getText()));
            manutencaoobra.setDs_servico(ds_servico.getText());
            manutencaoobra.setTp_obra(tp_obra);
        }
    }
}
